In [1]:
import torch
from torch.autograd import Variable

In [2]:
# Variable in torch is to build a computational graph,
# but this graph is dynamic compared with a static graph in Tensorflow or Theano.
# So torch does not have placeholder, torch can just pass variable to the computational graph.

In [3]:
tensor = torch.FloatTensor([[1,2],[3,4]])            # build a tensor
variable = Variable(tensor, requires_grad=True)      # build a variable, usually for compute gradients

In [4]:
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [5]:
t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2

In [6]:
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [7]:
v_out.backward() # backpropagation from v_out

In [8]:
# v_out = 1/4 * sum(variable*variable)
# d(v_out)/d(variable) = variable/2
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [9]:
print(variable) # this is data in variable format

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [10]:
print(variable.data)  # this is data in tensor format

tensor([[1., 2.],
        [3., 4.]])


In [11]:
print(variable.data.numpy())    # numpy format

[[1. 2.]
 [3. 4.]]
