In [2]:
import tensorflow as tf

In [3]:
x = tf.random.normal([4, 32, 32, 3])
print(x.shape)

(4, 32, 32, 3)


In [5]:
print((x + tf.random.normal([3])).shape)
# 维度在计算的时候会从右向左补齐
# 补齐步骤 目标是 (4, 32, 32, 3) 首先 (3) 发现和前一个最后维度一样就会转换维度 (1, 1, 1, 3) 然后转换为 (4, 32, 32, 3)

(4, 32, 32, 3)


In [6]:
print((x + tf.random.normal([32, 32, 1])).shape)

(4, 32, 32, 3)


In [7]:
print((x + tf.random.normal([4, 1, 1, 1])).shape)

(4, 32, 32, 3)


In [9]:
# print((x + tf.random.normal([1, 4, 1, 1])).shape)
# 报错维度不可能补齐 

In [11]:
b = tf.broadcast_to(tf.random.normal([4, 1, 1, 1]), [4, 32, 32, 3])
print(b.shape)
# 上面都是通过隐式的转换，这里演示的是显示的维度转换

(4, 32, 32, 3)


In [12]:
a = tf.ones([3, 4])
print(a)
a1 = tf.broadcast_to(a, [2, 3, 4])
print(a1)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [14]:
# 在 0 位置增加一个维度
a2 = tf.expand_dims(a, axis=0)
print(a2)
# 在第一个维度复制两次 第二维度复制一次
a2 = tf.tile(a2, [2, 1, 1])
print(a2)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
