In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 通过 numpy 或 list 转换为 tensor
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [3]:
tf.convert_to_tensor(np.zeros([2, 3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [4]:
tf.convert_to_tensor([1, 2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
tf.convert_to_tensor([1, 2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [6]:
tf.convert_to_tensor([[1], [2.]]) # 数据不一致会自动转换为存储空间大的类型

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [7]:
# tf.zeros
print(tf.zeros([])) # 标量为 0 没有维度
print(tf.zeros([1]))
print(tf.zeros([1, 2]))
print(tf.zeros([1, 2, 3]))
print(tf.zeros([1]))

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


In [8]:
a = tf.zeros([2, 3, 3])
# 一下两个语句生成数据相同
print(tf.zeros_like(a))
print(tf.zeros(a.shape))

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


In [9]:
# tf.ones
print(tf.ones(1))
print(tf.ones([]))
print(tf.ones([2, 3]))
a = tf.ones([2, 3, 3])
# 一下两个语句生成数据相同
print(tf.ones_like(a))
print(tf.ones(a.shape))

tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [10]:
# tf.fill 第一个参数是一个 shape 第二个参数是生成数据
print(tf.fill([2, 2], 0))
print(tf.fill([2, 2], 0.))
print(tf.fill([2, 2], 1))
print(tf.fill([2, 2], 9))

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


In [11]:
# tf.random 随机初始化
# tf.random.normal 正态分布
tf.random.normal([2, 2], mean=1, stddev=1) # mean 均值 stddev 方差 正态分布初始化（虽然是随机初始化但是初始化数据服从正态分布）

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.3679998 ,  0.5780983 ],
       [ 0.52301157,  2.0574553 ]], dtype=float32)>

In [12]:
tf.random.normal([2, 2]) # 默认是 0，1 分布

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.8364406 ,  0.5968722 ],
       [ 0.27776608, -1.223464  ]], dtype=float32)>

In [13]:
tf.random.truncated_normal([2, 2]) # 正态分布初始化但是会截去一部分
# 如果你了解 sigmoid 函数你就会发现这个函数的图像超过某个特定值后求导其倒数接近于 0 这样就可能导致梯度下降的速度非常缓慢
# 所以就需要截去一部分

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.31324774,  1.9299513 ],
       [ 0.48700115, -0.16823606]], dtype=float32)>

In [14]:
# tf.random.uniform 均匀分布
tf.random.uniform([2, 2], minval=0, maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.08510041, 0.4069749 ],
       [0.11524642, 0.17979681]], dtype=float32)>

In [15]:
tf.random.uniform([2, 2], minval=0, maxval=100)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[92.396805, 76.74985 ],
       [65.05815 , 88.30634 ]], dtype=float32)>

In [16]:
# Random Permutation
'''
解释 Random Permutation
这是原始数据
[0, 1, 2]
这是打散后的数据
[2, 1, 0] （1）

# 这是第二批原始数据
[7, 6, 3]
# 在（1）的作用下上面数据就会被打散成和（1）打散位置一样的数据比如 0 -> 最后位置
                                                         7 -> 最后位置
[3, 6, 7]
'''
idx = tf.range(10)
# 打散
idx = tf.random.shuffle(idx)
print(idx)
a = tf.random.normal([10, 2])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)
print(a)
print(b)
a = tf.gather(a, idx)
b = tf.gather(b, idx)
print(a)
print(b)

tf.Tensor([3 5 7 8 1 2 4 9 0 6], shape=(10,), dtype=int32)
tf.Tensor(
[[ 0.8618773  -0.19166827]
 [ 0.8756172  -1.6987313 ]
 [ 1.5433981   2.5783927 ]
 [ 0.9826116   1.4398059 ]
 [-1.4711508   1.7537258 ]
 [-0.4527294   0.5957894 ]
 [-0.38101038  1.1836839 ]
 [ 1.665944   -0.39071426]
 [ 0.21543248 -1.3069894 ]
 [ 1.6591469   1.1265639 ]], shape=(10, 2), dtype=float32)
tf.Tensor([4 3 7 4 1 8 0 0 8 0], shape=(10,), dtype=int32)
tf.Tensor(
[[ 0.9826116   1.4398059 ]
 [-0.4527294   0.5957894 ]
 [ 1.665944   -0.39071426]
 [ 0.21543248 -1.3069894 ]
 [ 0.8756172  -1.6987313 ]
 [ 1.5433981   2.5783927 ]
 [-1.4711508   1.7537258 ]
 [ 1.6591469   1.1265639 ]
 [ 0.8618773  -0.19166827]
 [-0.38101038  1.1836839 ]], shape=(10, 2), dtype=float32)
tf.Tensor([4 8 0 8 3 7 1 0 4 0], shape=(10,), dtype=int32)


In [17]:
# tf.constant
print(tf.constant(1))
print(tf.constant([1]))
print(tf.constant([1, 2.]))
# print(tf.constant([1, 2.], [3.])) 维度必须统一不然就会报错

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [19]:
# loss
out = tf.random.uniform([4, 10]) # 4 行 10 列
y = tf.range(4)
y = tf.one_hot(y, depth=10)
loss = tf.keras.losses.mse(y, out)
print(loss)
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor([0.48116523 0.16928735 0.37546784 0.3427232 ], shape=(4,), dtype=float32)
tf.Tensor(0.34216088, shape=(), dtype=float32)


In [26]:
# vector
import tensorflow.keras.layers as layers 
net = layers.Dense(10)
net.build((4, 8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-3.36569697e-01,  8.42129588e-02,  5.34676075e-01,
         2.12073565e-01,  3.07044387e-02, -3.21870238e-01,
        -2.46643931e-01,  1.28141403e-01, -1.48624152e-01,
        -8.05796683e-02],
       [-4.72958744e-01,  3.01041424e-01, -1.75191343e-01,
        -4.66376543e-01, -4.83682305e-01, -3.30817521e-01,
         3.24930906e-01,  3.85928631e-01,  1.04414344e-01,
         8.18460584e-02],
       [ 2.87821412e-01,  9.88650322e-03, -5.39253294e-01,
         4.50507164e-01,  2.56847739e-01, -2.38685101e-01,
        -6.76333904e-03, -4.68426585e-01,  6.27140999e-02,
         2.89607048e-02],
       [ 4.77503896e-01,  1.44028664e-01, -2.51032263e-01,
         3.18959057e-01, -3.81487846e-01, -3.77306432e-01,
        -8.73368979e-03, -1.92631602e-01, -3.82272065e-01,
        -2.21477479e-01],
       [ 3.96195054e-01,  4.08267856e-01,  9.77048278e-02,
         3.37815583e-01, -1.07337236e-02,  9.92764235e-02,
        -5

In [27]:
net.bias # b

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [31]:
# matrix
x = tf.random.normal([4, 784])
net = layers.Dense(10)
net.build((4, 784))
net(x).shape

TensorShape([4, 10])

In [32]:
print(net.kernel.shape)
print(net.bias.shape)

(784, 10)
(10,)
