In [1]:
import tensorflow as tf

$$
Eukl Norm ||x|| = [\sum_{k}{x^2_k}]^{1/2} \\
Max Norm ||x|| = maxx_k|x_k| \\
L_1 Norm ||x|| = \sum_{K}{|x_k|}
$$

In [2]:
# Vertor Norm
# 二范数平方和开根号
a = tf.ones([2, 2])
print(tf.norm(a))

tf.Tensor(2.0, shape=(), dtype=float32)


In [3]:
b = tf.ones([2, 2])
# 一维度的二范数
print(tf.norm(b, ord=2, axis=1))
# 零维度的一范数
print(tf.norm(b, ord=1, axis=0))
# 一维度的一范数
print(tf.norm(b, ord=1, axis=1))

tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)
tf.Tensor([2. 2.], shape=(2,), dtype=float32)


In [4]:
# reduce_min/max/mean
a = tf.random.normal([4, 10])
tf.reduce_min(a),tf.reduce_max(a),tf.reduce_mean(a)

(<tf.Tensor: shape=(), dtype=float32, numpy=-2.6196685>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.8081744>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.08514073>)

In [5]:
# 在一维度求min max mean
tf.reduce_min(a, axis=1),tf.reduce_max(a, axis=1),tf.reduce_mean(a, axis=1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-2.6196685 , -1.6165125 , -1.3018146 , -0.65737146], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.53919554, 1.8081744 , 1.3424035 , 1.6555741 ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.41611257,  0.1153239 ,  0.32395333,  0.31739816], dtype=float32)>)

In [9]:
# argmax/argmin 返回最大值或最小值的位置
a = tf.random.normal([4, 2])
print(a)
print(tf.argmax(a))
print(tf.argmin(a))
print(tf.argmax(a, axis=1))

tf.Tensor(
[[ 0.21079707  0.08535914]
 [-1.5163007  -0.8349133 ]
 [ 0.09391207 -0.66254884]
 [-0.3262033   0.60264426]], shape=(4, 2), dtype=float32)
tf.Tensor([0 3], shape=(2,), dtype=int64)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor([0 1 0 1], shape=(4,), dtype=int64)


In [12]:
# equal
a = tf.constant([1, 2, 3, 4, 4])
b = tf.range(5)
ref = tf.equal(a, b)
print(ref)

In [14]:
# tf.cast 转换类型 tf.reduce_sum 累加（这条语句可以统计上面 equal 中匹配数）
tf.reduce_sum(tf.cast(ref, dtype=tf.int32))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [17]:
# unique 去除重复元素
a = tf.constant([4, 2, 2, 4, 3])
ref = tf.unique(a) # [4, 2, 3] 去除重复之后的结果 [0, 1, 1, 0, 2] 可以通过这张表还原以前的数据对应的是新生成表的索引
print(ref)

Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3], dtype=int32)>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2], dtype=int32)>)


In [21]:
tf.gather(ref[0], ref[1]) # 还原

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 2, 2, 4, 3], dtype=int32)>