In [1]:
import tensorflow as tf

In [4]:
# pad
a = tf.reshape(tf.range(9), [3, 3])
print(a)
print(tf.pad(a, [
    [0, 0], # 行
    [0, 0]  # 列
]))
print(tf.pad(a, [
    [1, 0],
    [0, 0]
]))
print(tf.pad(a, [
    [1, 1],
    [0, 0]
]))
print(tf.pad(a, [
    [1, 1],
    [1, 0]
]))
print(tf.pad(a, [
    [1, 1],
    [1, 1]
]))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 1 2]
 [3 4 5]
 [6 7 8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 0 0]], shape=(5, 3), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 1 2]
 [0 3 4 5]
 [0 6 7 8]
 [0 0 0 0]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]], shape=(5, 5), dtype=int32)


In [6]:
# 假设有四张 28*28 三通道的照片
a = tf.random.normal([4, 28, 28, 3])
print(a.shape)
# 给照片加上下左右都加一
b = tf.pad(a, [
    [0, 0],
    [1, 1],
    [1, 1],
    [0, 0]
])
print(b.shape)

(4, 28, 28, 3)
(4, 30, 30, 3)


In [10]:
# tile 复制
a = tf.reshape(tf.range(9), [3, 3])
print(tf.tile(a, [1, 2])) # 行维度不变 列维度复制两次
print(tf.tile(a, [2, 1])) 
print(tf.tile(a, [2, 2]))

tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(3, 6), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]], shape=(6, 3), dtype=int32)
tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(6, 6), dtype=int32)


In [16]:
# tile Vs broadcast_to
# 添加一个维度
aa = tf.expand_dims(a, axis=0)
print(aa.shape)
print(tf.tile(aa, [2, 1, 1])) 
print(tf.broadcast_to(aa, [2, 3, 3])) 
# 结果没有区别 但是broadcast_to是在运行时才完成，所有性能更加高

(1, 3, 3)
tf.Tensor(
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]], shape=(2, 3, 3), dtype=int32)
