In [2]:
import tensorflow as tf

In [3]:
a = tf.ones([1, 5, 5, 3]) # 四维
a[0][0]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [5]:
a[0][0][0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [6]:
a[0, 0, 0] # 尽量用这种方式取值

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [7]:
a = tf.random.normal([4, 28, 28, 3])
print(a[1].shape)
print(a[1, 2].shape)
print(a[1, 2, 3].shape)
print(a[1, 2, 3, 2].shape)

(28, 28, 3)
(28, 3)
(3,)
()


In [8]:
a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [9]:
a[-1:] # 负数从后往前数 以下所有方式返回的都是向量

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9], dtype=int32)>

In [10]:
a[-2:] # 从 倒数第二 到 最后

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9], dtype=int32)>

In [11]:
a[: 2] # 从 0 到 2（这里就是第2个元素也就是 1）

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [12]:
a[: -1] # 从 0 到 -1（这里就是第9个元素也就是 8）

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [16]:
a = tf.random.normal([4, 28, 28, 3])
print(a.shape)
print(a[0].shape)
print(a[0, :, :, :].shape)
print(a[0, 1, :, :].shape)
print(a[:, :, :, 0].shape)
print(a[:, :, :, 2].shape)
print(a[:, 0, :, :].shape)

(4, 28, 28, 3)
(28, 28, 3)
(28, 28, 3)
(28, 3)
(4, 28, 28)
(4, 28, 28)
(4, 28, 3)


In [19]:
# indexing by :: 隔着采样
# start:end:step
print(a[:, 0:28:2, 0:28:2, :].shape)
print(a[:, ::2, ::2, :].shape)

(4, 14, 14, 3)
(4, 14, 14, 3)


In [20]:
# ::-1 倒着采样
a = tf.range(4)
print(a)
print(a[::-1])
print(a[::-2])
print(a[2::-2])

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 0], shape=(4,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor([2 0], shape=(2,), dtype=int32)


In [23]:
# ...
a = tf.random.normal([4, 28, 28, 3])
print(a[0, ...].shape)
print(a[0, ..., 2].shape)

(28, 28, 3)
(28, 28)


In [28]:
# selective indexing
a = tf.random.normal([4, 35, 8])
print(tf.gather(a, axis=0, indices=[2, 3]).shape) # 这条语句的含义是，操作数据源 a 操作的维度是 0 取0维度的 2，3（下标）
print(tf.gather(a, axis=0, indices=[0, 2, 3, 1]).shape)
print(tf.gather(a, axis=1, indices=[10, 2, 18, 9]).shape)

(2, 35, 8)
(4, 35, 8)
(4, 4, 8)


In [32]:
a = tf.random.normal([4, 35, 8])
print(tf.gather_nd(a, [0]).shape) # 可以理解成 a[0]
print(tf.gather_nd(a, [0, 1]).shape) # a[0, 1]
print(tf.gather_nd(a, [0, 1, 2]).shape) # a[0, 1, 2]
print(tf.gather_nd(a, [[0, 1, 2]]).shape) # [a[0, 1, 2]]
print(tf.gather_nd(a, [[0, 1], [0, 3], [0, 5]]).shape) # [a[0, 1], a[0, 3], a[0, 5]]
print(tf.gather_nd(a, [[[0, 1, 1], [0, 1, 2], [3, 4, 2]]]).shape)

(35, 8)
(8,)
()
(1,)
(3, 8)
(1, 3)


In [36]:
# tf.boolean_mask
a = tf.random.normal([4, 28, 28, 3])
print(tf.boolean_mask(a, mask=[True, True, False, False]).shape) # 可以理解成第一维也就是4中取前两组
print(tf.boolean_mask(a, mask=[False, True, False], axis=3).shape) # 可以理解成第四维中取中间那组
a = tf.ones([2, 3, 4])
print(tf.boolean_mask(a, [[True, False, False], [True, True, False]])) # [2, 3] 中 取 [0, 0] [1, 0] [1, 1] 

(2, 28, 28, 3)
(4, 28, 28, 1)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
