In [2]:
import tensorflow as tf

In [3]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [6]:
# tf.constant(2.2, dtype=tf.int32) # type error

In [7]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [8]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [9]:
tf.constant('hello word')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello word'>

In [21]:
with tf.device('cpu'):
    a = tf.constant([1])
with tf.device('gpu'): # 我的电脑上面没有GPU环境
    b = tf.range(4)
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [22]:
b.device # 还是 CPU 环境 因为我的电脑上面没有 GPU 环境

'/job:localhost/replica:0/task:0/device:CPU:0'

In [23]:
a.numpy() # tensor 转换为 numpy

array([1], dtype=int32)

In [29]:
a.ndim

1

In [30]:
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [32]:
tf.rank(tf.ones([3, 2, 1]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [34]:
import numpy as np
a = tf.constant([1.])
b = tf.constant([True, False])
c = tf.constant('hello world')
d = np.arange(4)

In [36]:
print(isinstance(a, tf.Tensor))
print(tf.is_tensor(a)) # 判断 a 是不是 tensor

True
True


In [37]:
tf.is_tensor(d)

False

In [38]:
a.dtype, b.dtype, c.dtype

(tf.float32, tf.bool, tf.string)

In [39]:
a.dtype == tf.float32

True

In [40]:
c.dtype == tf.string

True

In [44]:
a = np.arange(5)
a.dtype

dtype('int64')

In [46]:
aa = tf.convert_to_tensor(a) # 从 numpy 数据转换为 tensor 数据
aa # 输出的还是 int64 和上面一样

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [47]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)
aa

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [48]:
tf.cast(aa, dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [50]:
aaa =tf.cast(aa, dtype=tf.double)
aaa

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [51]:
tf.cast(aaa, dtype=tf.int32)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [54]:
b = tf.constant([0, 1])
bb = tf.cast(b,dtype=tf.bool)
bb

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [55]:
tf.cast(bb, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [58]:
a = tf.range(5)
b = tf.Variable(a) # 专门为参数所设定的一种类型 tensorflow 在处理这种数据时会专门记录其梯度信息
print(b.dtype)
print(b.name)

<dtype: 'int32'>
Variable:0


In [59]:
print(isinstance(b, tf.Variable))
print(isinstance(b, tf.Tensor))
print(tf.is_tensor(b)) # 不推荐使用 isinstance 来判断类型

True
False
True


In [60]:
# tensor 转换为 numpy
a = tf.constant([1, 2, 3, 4, 5])
a.numpy()

array([1, 2, 3, 4, 5], dtype=int32)

In [62]:
a = tf.ones([])
print(a.numpy())
print(int(a))
print(float(a))

1.0
1
1.0


In [ ]:
# tensor 是一种数据载体 tensor 在这个框架流动 所以这个框架就叫 tensorflow